[package]
name = "portus-window-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
clap.workspace = true
portus-window-protocol = { version = "=0.1.0", path = "../portus-window-protocol" }
serde_json.workspace = true
tokio.workspace = true
